name: Linting with black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint with Black
        uses: psf/black@stable
        with:
          args: main.py
